### ISSUE TITLE
Handle components that return null from render()

### ISSUE THREAD

**Issue by dallonf** [loggur/babel-plugin-react-error-catcher#10]
So, I promised a pull request to fix my remaining issues. I lied. :frowning: Could only figure out [one of them](https://github.com/loggur/babel-plugin-react-error-catcher/pull/9) on my own.

In React, it is acceptable to return `false` or `null` from a `render()` function. (https://facebook.github.io/react/docs/component-specs.html#render) This causes the component not to appear in the DOM at all. However, this plugin seems to assume that a null value returned from `render` is an error state and fills in any null components with dark red boxes. Unfortunately, this started taking a long time to fix and would require me setting up a dev environment, so I had to back off. I'll revisit this during the weekend if I can.

**Comment by timbur** [comment]
Thanks again for the feedback!  Try `v1.1.11` and let me know how it goes.

**Comment by dallonf** [comment]
Works like a charm! :grin: Thanks
