### ISSUE TITLE
Seems to break source maps in some cases

### ISSUE THREAD

**Issue by jedwards1211** [loggur/babel-plugin-react-error-catcher#11]
I'm still confused about what's going on here, but when I use this with `redbox-react` or `delicate-error-reporter`, the source maps don't quite seem to work.  Here's a screenshot.  You can see that it shows `ProxyClass` instead of `App.jsx`.  Also the error printed to the console links directly into the webpack bundle instead of the original source.

![image](https://cloud.githubusercontent.com/assets/1448194/9829631/1cee731a-58d2-11e5-94aa-ed0e1d76c945.png)

This was first brought to my attention here: https://github.com/jedwards1211/meteor-webpack-react/issues/40

Reproducible with the latest version of `meteor-webpack-react`: https://github.com/jedwards1211/meteor-webpack-react/commit/353f8c46b279ebcd514c34af9958144630b2d5ef

We are doing one weird thing in that project: serving the webpack bundle from `localhost:9090` whereas the rest of the page is served by Meteor from `localhost:3000`.

Any ideas what would be the issue?

**Comment by jedwards1211** [comment]
whooooooops wrong project, we're using `react-transform-error-catcher`.  Too many tools!

**Comment by timbur** [comment]
Haha no problemo.
