### ISSUE TITLE
displayName lost

### ISSUE THREAD

**Issue by glenjamin** [loggur/babel-plugin-react-error-catcher#4]
When using this plugin, the displayName property when using React.createClass is lost - presumably due to the transform.

Is there any way to retain this?

PS. this plugin is ace!

**Comment by timbur** [comment]
Nice *catch*!  😂

I believe it's fixed now in v1.1.5.  Please let me know if it isn't!

I also noticed a misleading warning when `createClass` is used and fixed that.

> PS. this plugin is ace!

TY!

**Comment by glenjamin** [comment]
Confirmed that this and the spurious warning are both fixed now.

The Error component still doesn't have a name, but that's not really a problem.
