### ISSUE TITLE
childContextTypes must be defined in order to use getChildContext()

### ISSUE THREAD

**Issue by dallonf** [loggur/babel-plugin-react-error-catcher#8]
When I included this plugin in my app, I got this error and was unable to render: 

`Invariant Violation: App.getChildContext(): childContextTypes must be defined in order to use getChildContext().`

Unfortunately I don't understand how this project works well enough to provide much more useful information, but here are some more details about my app that can hopefully help?

* I'm using React Router 0.13 - there do seem to be some bits related to the Router in the stack trace so that might be important
* I use Context pretty extensively on my own

I'll see if I can create a small repro project later.

**Comment by timbur** [comment]
Hello!  See https://github.com/loggur/babel-plugin-react-error-catcher/issues/6#issuecomment-135833276 to the end.  Updating to `v1.1.9` should hopefully fix that for you.

**Comment by dallonf** [comment]
Hi there! Thanks for the quick response. I actually am using v1.1.9 already. I wonder if some of the higher-order components and decorators I'm using (especially react-redux's `@connect`) are throwing it off?

**Comment by timbur** [comment]
May I see your config?

**Comment by dallonf** [comment]
Wow! That was a painful repro. It appears to be a combination of a HOC and a mixin (applied via the react-mixin decorator) that triggers the issue. Specifically in my project, it's the combination of Redux's `@connect` decorator and react-intl's `IntlMixin`.

Here's a repro project (forked from essential-react) that shows the issue: https://github.com/dallonf/essential-react/releases/tag/babel-plugin-react-error-catcher-repro

I realize this is insanely specific to my use case, so let me know if there's anything I can do to help fix or work around this :smile:

**Comment by timbur** [comment]
It's probably a case of multiple monkey-patches, and then I bet it's essentially the same issue in #6 where React is checking a monkey-patched constructor and not finding `childContextTypes`.  Trying out your repro repo now.

**Comment by timbur** [comment]
Try `v1.1.10`.  I've ensured (or tried to ensure) that the `error-catcher` decorator receives the component class first.  No idea if that will actually resolve your issue so let me know.  :)

**Comment by dallonf** [comment]
Thanks! That seems to have resolved this particular issue. PR inbound for a few others I've been having, but think I can fix...
